# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MeDS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeDS

   pod 'SwiftSocket'

  target 'MeDSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeDSUITests' do
    # Pods for testing
  end

end
